spring:
  application:
    name: GlobalSolutionJava
  messages:
    basename: messages
    encoding: UTF-8
  data:
    web:
      pageable:
        one-indexed-parameters: true

  datasource:
    url: jdbc:oracle:thin:@//oracle.fiap.com.br:1521/ORCL
    username: RM558961
    password: fiap25
    driver-class-name: oracle.jdbc.driver.OracleDriver
    jpa:
      database-platform: org.hibernate.dialect.OracleDialect
      properties:
        hibernate.format_sql: true
    # spring.jpa.show-sql: true
    # spring.jpa.hibernate.ddl-auto: create-drop

  port: 8080

api:
  security:
    token:
      secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30