azure:
  storage:
    connection-string: DefaultEndpointsProtocol=https;AccountName=SEU_ACCOUNT;AccountKey=SUA_KEY;EndpointSuffix=core.windows.net
    queue-name: minha-fila-teste

api:
  security:
    token:
      secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30

gemini:
  api:
    key: AIzaSyCC1UcVQFdHGoTREY2cCpEdu2CR2WCR53Y
  model: gemini-2.5-flash